---
name: Release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_release_callable.yml@9bd314f6b4e4ce78759173cb4aab29c476426e69
    secrets: inherit
