---
name: Renovate

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "37 0/6 * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # yamllint disable-line rule:comments
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Self-hosted Renovate
        # yamllint disable-line rule:comments
        uses: renovatebot/github-action@0c3fbdc6346afb523f8f993c0d6888c5db277ac8 # v34.136.0
        with:
          configurationFile: default.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          GITHUB_COM_TOKEN: ${{ secrets.RENOVATE_GITHUB_COM_TOKEN }}
