---
name: Renovate

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "37 0/6 * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v34.82.0
        with:
          configurationFile: default.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          GITHUB_COM_TOKEN: ${{ secrets.RENOVATE_GITHUB_COM_TOKEN }}
