---
name: Renovate

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # yamllint disable-line rule:comments
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Self-hosted Renovate
        # yamllint disable-line rule:comments
        uses: renovatebot/github-action@299cbf941792d474b268c2c486505a04f632e89e # v34.138.3
        with:
          configurationFile: default.json
          token: ${{ secrets.RENOVATE_TOKEN }}
          useSlim: false
        env:
          GITHUB_COM_TOKEN: ${{ secrets.RENOVATE_GITHUB_COM_TOKEN }}
          LOG_LEVEL: debug
