---
name: PR commented

# yamllint disable-line rule:truthy
on:
  issue_comment:
    types:
      - created

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_slash_ops_comment_dispatch_callable.yml@7a25f9892f38ee19a3abff5f7e4696b54166d8e5 # 1.20.6
    secrets: inherit
