name: 'Check spelling'

on:
  pull_request:

jobs:
  cspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.1
      - uses: streetsidesoftware/cspell-action@v2.19.0
        with:
          config: .config/cspell.json