---
name: "Close stale issues and PRs"

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "25 2 * * *"

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_stale_callable.yml@8b195a48d81723deddedfb5fc10159fb1c2bbd4e # 1.15.7
    secrets: inherit
